{"uuid": "7a48ddae-cd81-4117-9fc8-8d14f1b4945c", "children": ["2e9db42a-5502-44af-b4ce-9d216891b6f6", "b966d4b4-27b0-472e-acac-1f7f8048e8ac"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=84.0.4147.105)\n\n", "trace": "  File \"D:\\python3.7\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python3.7\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python3.7\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"D:\\pycharm\\projects\\OA_AUTOUI\\TestCase\\conftest.py\", line 42, in login\n    common()\n  File \"D:\\pycharm\\projects\\OA_AUTOUI\\TestCase\\conftest.py\", line 21, in common\n    driver.maximize_window()\n  File \"D:\\python3.7\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 737, in maximize_window\n    self.execute(command, params)\n  File \"D:\\python3.7\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python3.7\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1596194361998, "stop": 1596194457473}], "start": 1596194361998, "stop": 1596194457602}